### ISSUE TITLE
Script not working, no error returned

### ISSUE THREAD

**Issue by StarkITA** [denouche/ovh-dyndns#3]
Hello,

first and foremost, I must warn that I am running FreeNAS, and that I am running the script in a Jail.

I modified all .sh files to have #!/usr/local/bin/bash, since it is FreeBSD default path.

That said, I have followed the instructions, but to no avail, since I have no zone updated, and no error returned.

Is there a way to debug this?

**Comment by denouche** [comment]
Hello,

Can you run the script manually and get the output?

Le 21 août 2017 7:36 AM, "Lorenzo Rosei" <notifications@github.com> a
écrit :

**Comment by StarkITA** [comment]
Output:

```
[root@scripts /scripts/ovh-dyndns]# bash -x ovh-dyndns.sh --domain xyz.ovh
+ LIBS=libs
+ GET_IP_URL=http://ipecho.net/plain
+++ dirname ovh-dyndns.sh
++ cd .
++ pwd
+ CURRENT_PATH=/scripts/ovh-dyndns
+ API_TARGET=EU
+ main --domain xyz.ovh
+ parseArguments --domain xyz.ovh
+ '[' 2 -gt 0 ']'
+ case $1 in
+ shift
+ DOMAIN=xyz.ovh
+ shift
+ '[' 0 -gt 0 ']'
+ checkArgumentsValids
+ '[' -z xyz.ovh ']'
+ checkInternetConnexion
+ ping -c1 -w2 8.8.8.8
+ '[' 64 -ne 0 ']'
+ exit 2
```

EDIT: Reading the code, seems working as intended? I mean, of course my ping to google will never be 0, so the following code will always make me exit.

```
checkInternetConnexion()
{
    ping -c1 -w2 8.8.8.8 &> /dev/null
    if [ $? -ne 0 ]
    then
        exit 2
    fi
}
```

Edit 2: if i change "-ne" to "-eq", the scripts goes on. Then the problem is aroun the "sha1sum" command, but I might just, after it's fixed, fork the script for freebsd usage :)

**Comment by denouche** [comment]
I think the ping command is blocked on FreeNAS. That's why ping give an return status > 0. Can you check if you can ping Google via command line?

Just need to remove the call to checkInternetConnexion to avoid calling the ping command. 

Maybe I can add an option to avoid checks, in some cases as your it can be useful, and avoid to fork the project.

**Comment by StarkITA** [comment]
For FreeBSD is still needed to change commands (such as sha1sum).

When I'll get back from work I'll start to look into that to check which commands give me error and how to correct it.

I think that it simply cannot work into FreeBSD without modifications.

**Comment by denouche** [comment]
Why are you talking about sha1sum command? This script does not use this command.

But I think your problem comes from the ping command, which is failing on FreeNAS: https://bugs.freenas.org/issues/7746

We can envisage some modifications in this script to feet the FreeNAS needs.

**Comment by StarkITA** [comment]
When I ran the script with trace, it called ovh-api.sh(not exact name),
which uses sha1sum, which failed because it is not existant on FreeBSD.

Il 21 ago 2017 09:42, "Antoine Leveugle" <notifications@github.com> ha
scritto:

**Comment by denouche** [comment]
Oh I see.
Maybe we could find a solution that works both on FreeNAS and others platforms, using another command instead of sha1sum.
Let me know I you find a solution for this command, it would be great to add FreeNAS compatibility.

**Comment by StarkITA** [comment]
I will look into it this afternoon or evening! :)

Il 21 ago 2017 09:52, "Antoine Leveugle" <notifications@github.com> ha
scritto:

**Comment by StarkITA** [comment]
The "problem is the following difference in the man pages for the command.

Linux:

> -w deadline
> Specify a timeout, in seconds, before ping exits regardless of how many packets have been sent or received. In this case ping does not stop after count packet are sent, it waits either for deadline expire or until count probes are answered or for some error notification from network.

BSD has no deadline. 

Only has timeout, which is, on Linux

> -W timeout
> Time to wait for a response, in seconds. The option affects only timeout in absense of any responses, otherwise ping waits for two RTTs.

And on BSD

>   -t timeout
> 	     Specify a timeout, in seconds, before ping exits regardless of
> 	     how many packets have been recieved.

I don't think there's a deadline option, for FreeBSD.

Omitting -w2 makes the script proceed.

wget needs to be added to the dependencies, for FreeBSD, also, since it's not included in base jail for example.

Once it's added, code proceeds until the call to ovh-api-bash-client.sh, which calls line sha1sum on line 138, not existant on FreeBSD.

[shasum](https://www.freebsd.org/cgi/man.cgi?query=shasum&sektion=1&manpath=freebsd-release-ports) is what could replace it, on BSD systems.

**Comment by StarkITA** [comment]
I haven't forgot, it's that my nas is down for the moment so I have no means to proceed :)
